// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SSGS_EMS_Test_Project
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// StartWinApp
        /// </summary>
        public void StartWinApp()
        {
            #region Variable Declarations
            WinButton uIStartButton = this.UIStartWindow.UIStartButton;
            WinMenuItem uIComputerMenuItem = this.UIStartmenuWindow.UIItemWindow.UIStartmenuClient.UIComputerMenuItem;
            WinEdit uISpaceusedEdit = this.UIComputerWindow.UIItemWindow.UILocalDiskCListItem.UISpaceusedEdit;
            WinEdit uINameEdit = this.UIComputerWindow.UIItemWindow1.UISSGSEMSListItem.UINameEdit;
            WinEdit uINameEdit1 = this.UIComputerWindow.UIItemWindow2.UISSGSEMSScrumListItem.UINameEdit;
            WinEdit uINameEdit2 = this.UIComputerWindow.UIItemWindow3.UISSGSEMSWinFormAppListItem.UINameEdit;
            WinEdit uINameEdit3 = this.UIComputerWindow.UIItemWindow4.UIBinListItem.UINameEdit;
            WinEdit uINameEdit4 = this.UIComputerWindow.UIItemWindow5.UIDebugListItem.UINameEdit;
            WinEdit uINameEdit5 = this.UIComputerWindow.UIItemWindow6.UISSGSEMSWinFormAppexeListItem.UINameEdit;
            #endregion

            // Click 'Start' button
            Mouse.Click(uIStartButton, new Point(36, 32));

            // Click 'Computer' menu item
            Mouse.Click(uIComputerMenuItem, new Point(31, 16));

            // Double-Click 'Space used' text box
            Mouse.DoubleClick(uISpaceusedEdit, new Point(33, 1));

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit, new Point(39, 8));

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit1, new Point(31, 15));

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit2, new Point(52, 15));

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit3, new Point(38, 14));

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit4, new Point(38, 14));

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit5, new Point(71, 9));
        }
        
        /// <summary>
        /// LoginWinApp - Use 'LoginWinAppParams' to pass parameters into this method.
        /// </summary>
        public void LoginWinApp()
        {
            #region Variable Declarations
            WinEdit uITxtUserEdit = this.UILoginWindow.UITxtUserWindow.UITxtUserEdit;
            WinEdit uITxtPwdEdit = this.UILoginWindow.UITxtPwdWindow.UITxtPwdEdit;
            WinButton uILoginButton = this.UILoginWindow.UILoginWindow1.UILoginButton;
            #endregion

            // Type 'shalaka' in 'txtUser' text box
            uITxtUserEdit.Text = this.LoginWinAppParams.UITxtUserEditText;

            // Type '{Tab}' in 'txtUser' text box
            Keyboard.SendKeys(uITxtUserEdit, this.LoginWinAppParams.UITxtUserEditSendKeys, ModifierKeys.None);

            // Type '********' in 'txtPwd' text box
            Keyboard.SendKeys(uITxtPwdEdit, this.LoginWinAppParams.UITxtPwdEditSendKeys, true);

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(39, 16));
        }
        
        /// <summary>
        /// ExecuteWinApp - Use 'ExecuteWinAppParams' to pass parameters into this method.
        /// </summary>
        public void ExecuteWinApp()
        {
            #region Variable Declarations
            WinEdit uITextBox1Edit = this.UISSGSEMSWindow.UITextBox1Window.UITextBox1Edit;
            WinButton uIGetBasicDataButton = this.UISSGSEMSWindow.UIGetBasicDataWindow.UIGetBasicDataButton;
            WinButton uIGetExtendedDataButton = this.UISSGSEMSWindow.UIGetExtendedDataWindow.UIGetExtendedDataButton;
            #endregion

            // Type '1' in 'textBox1' text box
            uITextBox1Edit.Text = this.ExecuteWinAppParams.UITextBox1EditText;

            // Click 'Get Basic Data' button
            Mouse.Click(uIGetBasicDataButton, new Point(15, 15));

            // Click 'Get Extended Data' button
            Mouse.Click(uIGetExtendedDataButton, new Point(15, 23));
        }
        
        /// <summary>
        /// CloseWinApp
        /// </summary>
        public void CloseWinApp()
        {
            #region Variable Declarations
            WinButton uICloseApplicationButton = this.UISSGSEMSWindow.UICloseApplicationWindow.UICloseApplicationButton;
            WinButton uICloseButton = this.UIComputerWindow.UIDebugTitleBar.UICloseButton;
            #endregion

            // Click 'Close Application' button
            Mouse.Click(uICloseApplicationButton, new Point(29, 21));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(28, 7));
        }
        
        #region Properties
        public virtual LoginWinAppParams LoginWinAppParams
        {
            get
            {
                if ((this.mLoginWinAppParams == null))
                {
                    this.mLoginWinAppParams = new LoginWinAppParams();
                }
                return this.mLoginWinAppParams;
            }
        }
        
        public virtual ExecuteWinAppParams ExecuteWinAppParams
        {
            get
            {
                if ((this.mExecuteWinAppParams == null))
                {
                    this.mExecuteWinAppParams = new ExecuteWinAppParams();
                }
                return this.mExecuteWinAppParams;
            }
        }
        
        public UIStartWindow UIStartWindow
        {
            get
            {
                if ((this.mUIStartWindow == null))
                {
                    this.mUIStartWindow = new UIStartWindow();
                }
                return this.mUIStartWindow;
            }
        }
        
        public UIStartmenuWindow UIStartmenuWindow
        {
            get
            {
                if ((this.mUIStartmenuWindow == null))
                {
                    this.mUIStartmenuWindow = new UIStartmenuWindow();
                }
                return this.mUIStartmenuWindow;
            }
        }
        
        public UIComputerWindow UIComputerWindow
        {
            get
            {
                if ((this.mUIComputerWindow == null))
                {
                    this.mUIComputerWindow = new UIComputerWindow();
                }
                return this.mUIComputerWindow;
            }
        }
        
        public UILoginWindow UILoginWindow
        {
            get
            {
                if ((this.mUILoginWindow == null))
                {
                    this.mUILoginWindow = new UILoginWindow();
                }
                return this.mUILoginWindow;
            }
        }
        
        public UISSGSEMSWindow UISSGSEMSWindow
        {
            get
            {
                if ((this.mUISSGSEMSWindow == null))
                {
                    this.mUISSGSEMSWindow = new UISSGSEMSWindow();
                }
                return this.mUISSGSEMSWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginWinAppParams mLoginWinAppParams;
        
        private ExecuteWinAppParams mExecuteWinAppParams;
        
        private UIStartWindow mUIStartWindow;
        
        private UIStartmenuWindow mUIStartmenuWindow;
        
        private UIComputerWindow mUIComputerWindow;
        
        private UILoginWindow mUILoginWindow;
        
        private UISSGSEMSWindow mUISSGSEMSWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginWinApp'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class LoginWinAppParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'shalaka' in 'txtUser' text box
        /// </summary>
        public string UITxtUserEditText = "shalaka";
        
        /// <summary>
        /// Type '{Tab}' in 'txtUser' text box
        /// </summary>
        public string UITxtUserEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'txtPwd' text box
        /// </summary>
        public string UITxtPwdEditSendKeys = "nIdgKjqy818SWf6/DXc3Y/uHJD8OtX1t";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ExecuteWinApp'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class ExecuteWinAppParams
    {
        
        #region Fields
        /// <summary>
        /// Type '1' in 'textBox1' text box
        /// </summary>
        public string UITextBox1EditText = "1";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIStartWindow : WinWindow
    {
        
        public UIStartWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Start";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public WinButton UIStartButton
        {
            get
            {
                if ((this.mUIStartButton == null))
                {
                    this.mUIStartButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIStartButton.SearchProperties[WinButton.PropertyNames.Name] = "Start";
                    this.mUIStartButton.WindowTitles.Add("Start");
                    #endregion
                }
                return this.mUIStartButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIStartButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIStartmenuWindow : WinWindow
    {
        
        public UIStartmenuWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Start menu";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DV2ControlHost";
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "7";
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public UIStartmenuClient UIStartmenuClient
        {
            get
            {
                if ((this.mUIStartmenuClient == null))
                {
                    this.mUIStartmenuClient = new UIStartmenuClient(this);
                }
                return this.mUIStartmenuClient;
            }
        }
        #endregion
        
        #region Fields
        private UIStartmenuClient mUIStartmenuClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIStartmenuClient : WinClient
    {
        
        public UIStartmenuClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIComputerMenuItem
        {
            get
            {
                if ((this.mUIComputerMenuItem == null))
                {
                    this.mUIComputerMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIComputerMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Computer";
                    this.mUIComputerMenuItem.WindowTitles.Add("Start menu");
                    #endregion
                }
                return this.mUIComputerMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIComputerMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIComputerWindow : WinWindow
    {
        
        public UIComputerWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Computer";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Computer");
            this.WindowTitles.Add("Local Disk (C:)");
            this.WindowTitles.Add("SSGS EMS");
            this.WindowTitles.Add("SSGS EMS Scrum");
            this.WindowTitles.Add("SSGS EMS WinForm App");
            this.WindowTitles.Add("bin");
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow2 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow2(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIItemWindow3 UIItemWindow3
        {
            get
            {
                if ((this.mUIItemWindow3 == null))
                {
                    this.mUIItemWindow3 = new UIItemWindow3(this);
                }
                return this.mUIItemWindow3;
            }
        }
        
        public UIItemWindow4 UIItemWindow4
        {
            get
            {
                if ((this.mUIItemWindow4 == null))
                {
                    this.mUIItemWindow4 = new UIItemWindow4(this);
                }
                return this.mUIItemWindow4;
            }
        }
        
        public UIItemWindow5 UIItemWindow5
        {
            get
            {
                if ((this.mUIItemWindow5 == null))
                {
                    this.mUIItemWindow5 = new UIItemWindow5(this);
                }
                return this.mUIItemWindow5;
            }
        }
        
        public UIItemWindow6 UIItemWindow6
        {
            get
            {
                if ((this.mUIItemWindow6 == null))
                {
                    this.mUIItemWindow6 = new UIItemWindow6(this);
                }
                return this.mUIItemWindow6;
            }
        }
        
        public UIDebugTitleBar UIDebugTitleBar
        {
            get
            {
                if ((this.mUIDebugTitleBar == null))
                {
                    this.mUIDebugTitleBar = new UIDebugTitleBar(this);
                }
                return this.mUIDebugTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        
        private UIItemWindow2 mUIItemWindow2;
        
        private UIItemWindow3 mUIItemWindow3;
        
        private UIItemWindow4 mUIItemWindow4;
        
        private UIItemWindow5 mUIItemWindow5;
        
        private UIItemWindow6 mUIItemWindow6;
        
        private UIDebugTitleBar mUIDebugTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Computer");
            #endregion
        }
        
        #region Properties
        public UILocalDiskCListItem UILocalDiskCListItem
        {
            get
            {
                if ((this.mUILocalDiskCListItem == null))
                {
                    this.mUILocalDiskCListItem = new UILocalDiskCListItem(this);
                }
                return this.mUILocalDiskCListItem;
            }
        }
        #endregion
        
        #region Fields
        private UILocalDiskCListItem mUILocalDiskCListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILocalDiskCListItem : WinListItem
    {
        
        public UILocalDiskCListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Local Disk (C:)";
            this.WindowTitles.Add("Computer");
            #endregion
        }
        
        #region Properties
        public WinEdit UISpaceusedEdit
        {
            get
            {
                if ((this.mUISpaceusedEdit == null))
                {
                    this.mUISpaceusedEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUISpaceusedEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Space used";
                    this.mUISpaceusedEdit.WindowTitles.Add("Computer");
                    #endregion
                }
                return this.mUISpaceusedEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUISpaceusedEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Local Disk (C:)");
            #endregion
        }
        
        #region Properties
        public UISSGSEMSListItem UISSGSEMSListItem
        {
            get
            {
                if ((this.mUISSGSEMSListItem == null))
                {
                    this.mUISSGSEMSListItem = new UISSGSEMSListItem(this);
                }
                return this.mUISSGSEMSListItem;
            }
        }
        #endregion
        
        #region Fields
        private UISSGSEMSListItem mUISSGSEMSListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISSGSEMSListItem : WinListItem
    {
        
        public UISSGSEMSListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "SSGS EMS";
            this.WindowTitles.Add("Local Disk (C:)");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Local Disk (C:)");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("SSGS EMS");
            #endregion
        }
        
        #region Properties
        public UISSGSEMSScrumListItem UISSGSEMSScrumListItem
        {
            get
            {
                if ((this.mUISSGSEMSScrumListItem == null))
                {
                    this.mUISSGSEMSScrumListItem = new UISSGSEMSScrumListItem(this);
                }
                return this.mUISSGSEMSScrumListItem;
            }
        }
        #endregion
        
        #region Fields
        private UISSGSEMSScrumListItem mUISSGSEMSScrumListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISSGSEMSScrumListItem : WinListItem
    {
        
        public UISSGSEMSScrumListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "SSGS EMS Scrum";
            this.WindowTitles.Add("SSGS EMS");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("SSGS EMS");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("SSGS EMS Scrum");
            #endregion
        }
        
        #region Properties
        public UISSGSEMSWinFormAppListItem UISSGSEMSWinFormAppListItem
        {
            get
            {
                if ((this.mUISSGSEMSWinFormAppListItem == null))
                {
                    this.mUISSGSEMSWinFormAppListItem = new UISSGSEMSWinFormAppListItem(this);
                }
                return this.mUISSGSEMSWinFormAppListItem;
            }
        }
        #endregion
        
        #region Fields
        private UISSGSEMSWinFormAppListItem mUISSGSEMSWinFormAppListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISSGSEMSWinFormAppListItem : WinListItem
    {
        
        public UISSGSEMSWinFormAppListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "SSGS EMS WinForm App";
            this.WindowTitles.Add("SSGS EMS Scrum");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("SSGS EMS Scrum");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow4 : WinWindow
    {
        
        public UIItemWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("SSGS EMS WinForm App");
            #endregion
        }
        
        #region Properties
        public UIBinListItem UIBinListItem
        {
            get
            {
                if ((this.mUIBinListItem == null))
                {
                    this.mUIBinListItem = new UIBinListItem(this);
                }
                return this.mUIBinListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIBinListItem mUIBinListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBinListItem : WinListItem
    {
        
        public UIBinListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "bin";
            this.WindowTitles.Add("SSGS EMS WinForm App");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("SSGS EMS WinForm App");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow5 : WinWindow
    {
        
        public UIItemWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("bin");
            #endregion
        }
        
        #region Properties
        public UIDebugListItem UIDebugListItem
        {
            get
            {
                if ((this.mUIDebugListItem == null))
                {
                    this.mUIDebugListItem = new UIDebugListItem(this);
                }
                return this.mUIDebugListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIDebugListItem mUIDebugListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIDebugListItem : WinListItem
    {
        
        public UIDebugListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Debug";
            this.WindowTitles.Add("bin");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("bin");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow6 : WinWindow
    {
        
        public UIItemWindow6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UISSGSEMSWinFormAppexeListItem UISSGSEMSWinFormAppexeListItem
        {
            get
            {
                if ((this.mUISSGSEMSWinFormAppexeListItem == null))
                {
                    this.mUISSGSEMSWinFormAppexeListItem = new UISSGSEMSWinFormAppexeListItem(this);
                }
                return this.mUISSGSEMSWinFormAppexeListItem;
            }
        }
        #endregion
        
        #region Fields
        private UISSGSEMSWinFormAppexeListItem mUISSGSEMSWinFormAppexeListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISSGSEMSWinFormAppexeListItem : WinListItem
    {
        
        public UISSGSEMSWinFormAppexeListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "SSGS EMS WinForm App.exe";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIDebugTitleBar : WinTitleBar
    {
        
        public UIDebugTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILoginWindow : WinWindow
    {
        
        public UILoginWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Login";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Login");
            #endregion
        }
        
        #region Properties
        public UITxtUserWindow UITxtUserWindow
        {
            get
            {
                if ((this.mUITxtUserWindow == null))
                {
                    this.mUITxtUserWindow = new UITxtUserWindow(this);
                }
                return this.mUITxtUserWindow;
            }
        }
        
        public UITxtPwdWindow UITxtPwdWindow
        {
            get
            {
                if ((this.mUITxtPwdWindow == null))
                {
                    this.mUITxtPwdWindow = new UITxtPwdWindow(this);
                }
                return this.mUITxtPwdWindow;
            }
        }
        
        public UILoginWindow1 UILoginWindow1
        {
            get
            {
                if ((this.mUILoginWindow1 == null))
                {
                    this.mUILoginWindow1 = new UILoginWindow1(this);
                }
                return this.mUILoginWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UITxtUserWindow mUITxtUserWindow;
        
        private UITxtPwdWindow mUITxtPwdWindow;
        
        private UILoginWindow1 mUILoginWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITxtUserWindow : WinWindow
    {
        
        public UITxtUserWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtUser";
            this.WindowTitles.Add("Login");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtUserEdit
        {
            get
            {
                if ((this.mUITxtUserEdit == null))
                {
                    this.mUITxtUserEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtUserEdit.SearchProperties[WinEdit.PropertyNames.Name] = "User Name";
                    this.mUITxtUserEdit.WindowTitles.Add("Login");
                    #endregion
                }
                return this.mUITxtUserEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtUserEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITxtPwdWindow : WinWindow
    {
        
        public UITxtPwdWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtPwd";
            this.WindowTitles.Add("Login");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtPwdEdit
        {
            get
            {
                if ((this.mUITxtPwdEdit == null))
                {
                    this.mUITxtPwdEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtPwdEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Password";
                    this.mUITxtPwdEdit.WindowTitles.Add("Login");
                    #endregion
                }
                return this.mUITxtPwdEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtPwdEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILoginWindow1 : WinWindow
    {
        
        public UILoginWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button1";
            this.WindowTitles.Add("Login");
            #endregion
        }
        
        #region Properties
        public WinButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new WinButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[WinButton.PropertyNames.Name] = "Login";
                    this.mUILoginButton.WindowTitles.Add("Login");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISSGSEMSWindow : WinWindow
    {
        
        public UISSGSEMSWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "SSGS EMS";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("SSGS EMS");
            #endregion
        }
        
        #region Properties
        public UITextBox1Window UITextBox1Window
        {
            get
            {
                if ((this.mUITextBox1Window == null))
                {
                    this.mUITextBox1Window = new UITextBox1Window(this);
                }
                return this.mUITextBox1Window;
            }
        }
        
        public UIGetBasicDataWindow UIGetBasicDataWindow
        {
            get
            {
                if ((this.mUIGetBasicDataWindow == null))
                {
                    this.mUIGetBasicDataWindow = new UIGetBasicDataWindow(this);
                }
                return this.mUIGetBasicDataWindow;
            }
        }
        
        public UIGetExtendedDataWindow UIGetExtendedDataWindow
        {
            get
            {
                if ((this.mUIGetExtendedDataWindow == null))
                {
                    this.mUIGetExtendedDataWindow = new UIGetExtendedDataWindow(this);
                }
                return this.mUIGetExtendedDataWindow;
            }
        }
        
        public UICloseApplicationWindow UICloseApplicationWindow
        {
            get
            {
                if ((this.mUICloseApplicationWindow == null))
                {
                    this.mUICloseApplicationWindow = new UICloseApplicationWindow(this);
                }
                return this.mUICloseApplicationWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITextBox1Window mUITextBox1Window;
        
        private UIGetBasicDataWindow mUIGetBasicDataWindow;
        
        private UIGetExtendedDataWindow mUIGetExtendedDataWindow;
        
        private UICloseApplicationWindow mUICloseApplicationWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITextBox1Window : WinWindow
    {
        
        public UITextBox1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox1";
            this.WindowTitles.Add("SSGS EMS");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox1Edit
        {
            get
            {
                if ((this.mUITextBox1Edit == null))
                {
                    this.mUITextBox1Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox1Edit.SearchProperties[WinEdit.PropertyNames.Name] = "Enter Employee ID";
                    this.mUITextBox1Edit.WindowTitles.Add("SSGS EMS");
                    #endregion
                }
                return this.mUITextBox1Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox1Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGetBasicDataWindow : WinWindow
    {
        
        public UIGetBasicDataWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button1";
            this.WindowTitles.Add("SSGS EMS");
            #endregion
        }
        
        #region Properties
        public WinButton UIGetBasicDataButton
        {
            get
            {
                if ((this.mUIGetBasicDataButton == null))
                {
                    this.mUIGetBasicDataButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIGetBasicDataButton.SearchProperties[WinButton.PropertyNames.Name] = "Get Basic Data";
                    this.mUIGetBasicDataButton.WindowTitles.Add("SSGS EMS");
                    #endregion
                }
                return this.mUIGetBasicDataButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIGetBasicDataButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIGetExtendedDataWindow : WinWindow
    {
        
        public UIGetExtendedDataWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button2";
            this.WindowTitles.Add("SSGS EMS");
            #endregion
        }
        
        #region Properties
        public WinButton UIGetExtendedDataButton
        {
            get
            {
                if ((this.mUIGetExtendedDataButton == null))
                {
                    this.mUIGetExtendedDataButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIGetExtendedDataButton.SearchProperties[WinButton.PropertyNames.Name] = "Get Extended Data";
                    this.mUIGetExtendedDataButton.WindowTitles.Add("SSGS EMS");
                    #endregion
                }
                return this.mUIGetExtendedDataButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIGetExtendedDataButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICloseApplicationWindow : WinWindow
    {
        
        public UICloseApplicationWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button3";
            this.WindowTitles.Add("SSGS EMS");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseApplicationButton
        {
            get
            {
                if ((this.mUICloseApplicationButton == null))
                {
                    this.mUICloseApplicationButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseApplicationButton.SearchProperties[WinButton.PropertyNames.Name] = "Close Application";
                    this.mUICloseApplicationButton.WindowTitles.Add("SSGS EMS");
                    #endregion
                }
                return this.mUICloseApplicationButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseApplicationButton;
        #endregion
    }
}
