ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [SSGS EMS Data], FILENAME = 'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\SSGS EMS Data.mdf', SIZE = 2304 KB, FILEGROWTH = 1024 KB) TO FILEGROUP [PRIMARY];

