ALTER TABLE [dbo].[EmpMaster]
    ADD CONSTRAINT [PK_EmpMaster] PRIMARY KEY CLUSTERED ([EmpId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

